#!/usr/bin/python3
import sys

cOption = True
wOption = True
lOption = True
mOption = False

def countLines(lines):
	lineCount = 0
	for line in lines:
		lineCount += 1
	return lineCount

def countWords(lines):
    wordCount = 0
    for line in lines:
        wordCount += len(line.split(' '))
    return wordCount

def countCharacters(lines):
    charCount = 0
    for line in lines:
        for character in line:
            charCount += 1
    return charCount


optionsFound = False
files = []
for i in range(1,len(sys.argv)):
	if sys.argv[i][0] != "-":
		files.append(sys.argv[i])
		openfile = open(files[0])
		string = openfile.read()

		#Found some options
		if not optionsFound:
			cOption = False
			wOption = False
			lOption = False
			optionsFound = True
		if "l" in sys.argv[i]:
			lOption = True
			if lOption == True:
				countLines(string)
		if "c" in sys.argv[i]:
			cOption = True
			if cOption == True:
				countCharacters(string)
		if "w" in sys.argv[i]:
			wOption = True
			if wOption == True:
				countWords(string)
		if "m" in sys.argv[i]:
			mOption = True




print(lineCount+"/t"+wordCount+"/t"+charCount+"/t"+files[0])

